name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
    REGISTRY: us-central1-docker.pkg.dev/molten-verve-216720
    REPOSITORY: ethereum-repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Registry login
      uses: docker/login-action@v2
      with:
        registry: ${REGISTRY}
        username: _json_key
        password: ${{ secrets.ANTITHESIS_LOGIN_FILE }}
    - name: Build and push etb-all-clients images
      timeout-minutes: 500
      run: |
          make build-etb-all-clients
          docker tag etb-all-clients:minimal ${REGISTRY}/${REPOSITORY}/etb-all-clients:minimal
          docker push ${REGISTRY}/${REPOSITORY}/etb-all-clients:minimal
          docker tag etb-all-clients:minimal-fuzz ${REGISTRY}/${REPOSITORY}/etb-all-clients:minimal
          docker push ${REGISTRY}/${REPOSITORY}/etb-all-clients:minimal-fuzz
          docker tag etb-all-clients-inst:minimal ${REGISTRY}/${REPOSITORY}/etb-all-clients:minimal
          docker push ${REGISTRY}/${REPOSITORY}/etb-all-clients-inst:minimal
